CREATE SCHEMA myScheme;
DROP TABLE IF EXISTS myScheme.STUDENT;
DROP TABLE IF EXISTS myScheme.STUDENT_INFO;
CREATE TABLE myScheme.STUDENT
(
    STUDENT_ID   SERIAL PRIMARY KEY,
    STUDENT_NAME VARCHAR(50) NOT NULL,
    STUDENT_AGE  VARCHAR(50) NOT NULL
);

CREATE TABLE myScheme.STUDENT_INFO
(
    STUDENT_ID      SERIAL PRIMARY KEY,
    ADDRESS         VARCHAR(50) NOT NULL,
    REGISTRY_NUMBER VARCHAR(50) NOT NULL,
    PHONE_NUMBER    VARCHAR(50) NOT NULL,
    CONSTRAINT FK_STUDENT_ID FOREIGN KEY (STUDENT_ID) REFERENCES myScheme.STUDENT (STUDENT_ID)
);
INSERT INTO myScheme.STUDENT(STUDENT_NAME, STUDENT_AGE)
VALUES ('Marina', '20');
INSERT INTO myScheme.STUDENT(STUDENT_NAME, STUDENT_AGE)
VALUES ('Vasya', '10');
INSERT INTO myScheme.STUDENT_INFO(ADDRESS, REGISTRY_NUMBER, PHONE_NUMBER)
VALUES ('belgorod 22', '5656', '+447688');
INSERT INTO myScheme.STUDENT_INFO(ADDRESS, REGISTRY_NUMBER, PHONE_NUMBER)
VALUES ('krasilova 15', '6656', '+347688');
COMMIT
