CREATE SCHEMA myScheme;
DROP TABLE IF EXISTS myScheme.Employee;
DROP TABLE IF EXISTS myScheme.Department;
CREATE TABLE myScheme.Employee
(
  EMP_ID   SERIAL PRIMARY KEY,
  EMP_NAME VARCHAR(50),
  EMP_AGE  INT
);

CREATE TABLE myScheme.Department
(
  DEP_ID      SERIAL PRIMARY KEY,
  EMP_ID      INT         NOT NULL,
  DEP_NAME    VARCHAR(50) NOT NULL,
  DESIGNATION VARCHAR(50),
  CONSTRAINT FK_EMP FOREIGN KEY (EMP_ID) REFERENCES myScheme.Employee (EMP_ID)
);
